export const FETCH_ART = 'FETCH_ART';
export const FETCH_ART_RECIEVED = 'FETCH_ART_RECIEVED';
export const FETCH_ART_REJECTED = 'FETCH_ART_REJECTED';

export const FETCH_TREES = 'FETCH_TREES';
export const FETCH_TREES_RECIEVED = 'FETCH_TREES_RECIEVED';
export const FETCH_TREES_REJECTED = 'FETCH_TREES_REJECTED';
