export const FETCH_ART = 'FETCH_ART';
export const FETCH_ART_RECIEVED = 'FETCH_ART_RECIEVED';
export const FETCH_ART_REJECTED = 'FETCH_ART_REJECTED';

export const FETCH_TREES = 'FETCH_TREES';
export const FETCH_TREES_RECIEVED = 'FETCH_TREES_RECIEVED';
export const FETCH_TREES_REJECTED = 'FETCH_TREES_REJECTED';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SELECT_ITEM = 'SELECT_ITEM';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_RECIEVED = 'FETCH_CATEGORIES_RECIEVED';
export const FETCH_CATEGORIES_REJECTED = 'FETCH_CATEGORIES_REJECTED';
